/* =========================================================
   data.js — seed content (default subjects + chapters)
   Edit this file to change the starting subject/chapter set.
   ========================================================= */

const QUOTES = [
  "Small progress every day leads to big success.",
  "Discipline is choosing between what you want now and what you want most.",
  "The expert in anything was once a beginner.",
  "It always seems impossible until it's done.",
  "Slow is smooth, smooth is fast.",
  "You don't have to be extreme, just consistent.",
];

/* Each subject: name, emoji, and a starting list of chapter titles.
   Chapter counts here are indicative starting points — add/edit/delete
   freely inside the app; everything persists in localStorage. */
const DEFAULT_SUBJECTS = [
  { name: "Polity", emoji: "⚖️", chapters: [
    "Historical Background", "Making of the Constitution", "Concept of Constitution",
    "Salient Features of the Constitution", "Preamble of the Constitution",
    "Union and its Territory", "Citizenship", "Fundamental Rights",
    "Directive Principles of State Policy", "Fundamental Duties",
    "Amendment of the Constitution", "Basic Structure of the Constitution",
    "Parliamentary System", "Federal System", "Centre–State Relations",
    "Inter-State Relations", "Emergency Provisions", "President", "Vice-President",
    "Prime Minister", "Central Council of Ministers", "Cabinet Committees",
    "Parliament", "Parliamentary Committees", "Parliamentary Forums", "Supreme Court",
    "Judicial Review", "Judicial Activism", "Public Interest Litigation", "Governor",
    "Chief Minister", "State Council of Ministers", "State Legislature", "High Court",
    "Subordinate Courts", "Tribunals",
    "National Consumer Disputes Redressal Commission", "Lok Adalat and Other Courts",
    "Panchayati Raj", "Municipalities", "Union Territories",
    "Scheduled and Tribal Areas", "Election Commission",
    "Union Public Service Commission", "State Public Service Commission",
    "Finance Commission", "Goods and Services Tax Council",
    "National Commission for Scheduled Castes",
    "National Commission for Scheduled Tribes",
    "National Commission for Backward Classes",
    "Special Officer for Linguistic Minorities",
    "Comptroller and Auditor General of India", "Attorney General of India",
    "Advocate General of the State", "Constitutional Prescriptions", "NITI Aayog",
    "National Human Rights Commission", "State Human Rights Commission",
    "National Commission for Women",
    "National Commission for Protection of Child Rights",
    "National Commission for Minorities", "Central Information Commission",
    "State Information Commission", "Central Vigilance Commission",
    "Central Bureau of Investigation", "Lokpal and Lokayuktas",
    "National Investigation Agency", "National Disaster Management Authority",
    "Bar Council of India", "Law Commission of India",
    "Delimitation Commission of India", "Co-operative Societies",
    "Official Language", "Public Services",
    "Rights and Liabilities of the Government",
    "Special Provisions Relating to Certain Classes",
    "Special Provisions for Some States", "Political Parties",
    "Role of Regional Parties", "Elections", "Election Laws", "Electoral Reforms",
    "Voting Behaviour", "Coalition Government", "Anti-Defection Law",
    "Pressure Groups", "National Integration", "Foreign Policy",
    "National Commission to Review the Working of the Constitution",
    "Landmark Judgements and Their Impact",
    "Important Doctrines of Constitutional Interpretation", "World Constitutions",
  ]},
  { name: "Economy", emoji: "📈", chapters: [
    "Basic Key Concepts", "National Income",
    "Economic Growth vs Economic Development",
    "Poverty, Inequality and Unemployment", "Inflation", "Indian Tax Structure",
    "Public Finance", "Economic Planning in India", "Money and Banking",
    "Financial Market", "Co-operative Sector in India", "Technology and Finance",
    "Agriculture and Allied Sectors", "Food Security and Food Management",
    "Land Reforms in India", "Irrigation in India", "Indian Industry", "MSME Sector",
    "Food Processing Industry in India", "Service Sector", "Infrastructure",
    "Health and Education", "Balance of Payments",
    "India’s Foreign Exchange and Foreign Trade",
    "International Economic Institutions", "Population and Demographic Dividend",
    "Skill Development", "Power and Energy Sector of India",
    "Care Economy and Gender Transformative Approach in India", "Investment Models",
    "Sustainable Development and Climate Change",
  ]},
  { name: "Geography", emoji: "🌍", chapters: [
    "Geography as a Discipline", "The Origin and Evolution of the Earth",
    "Interior of the Earth", "Distribution of Oceans and Continents",
    "Geomorphic Processes", "Landforms and Their Evolution",
    "Composition and Structure of the Atmosphere",
    "Solar Radiation, Heat Balance and Temperature",
    "Atmospheric Circulation and Weather Systems", "Water in the Atmosphere",
    "World Climate and Climate Change", "Water (Oceans)",
    "Movements of Ocean Water", "Biodiversity and Conservation", "India – Location",
    "Structure and Physiography", "Drainage System", "Climate",
    "Natural Vegetation", "Natural Hazards and Disasters",
    "Human Geography: Nature and Scope",
    "The World Population: Distribution, Density and Growth", "Human Development",
    "Primary Activities", "Secondary Activities",
    "Tertiary and Quaternary Activities", "Transport and Communication",
    "International Trade",
    "Population: Distribution, Density, Growth and Composition", "Human Settlements",
    "Land Resources and Agriculture", "Water Resources",
    "Mineral and Energy Resources",
    "Planning and Sustainable Development in Indian Context",
    "Transport and Communication (India)", "International Trade (India)",
    "Geographical Perspective on Selected Issues and Problems",
  ]},
  { name: "Environment", emoji: "🌱", chapters: [
    "Environment, Habitat and Ecosystem", "Ecology – Principles and Organizations",
    "Functions of an Ecosystem – Succession and Homeostasis",
    "Functions of an Ecosystem – Trophic Levels", "Biogeochemical Cycling",
    "Wetland Ecosystem", "Natural Ecosystems or Biomes",
    "Biodiversity and Loss of Biodiversity", "Biodiversity Conservation",
    "Wildlife Conservation Part I", "Wildlife Conservation Part II",
    "Air Pollution – Causes and Air Pollutants",
    "Air Pollution – Effects and Control Measures",
    "Water Pollution – Causes, Effects and Control Measures",
    "Plastic Pollution, Solid, Hazardous and E-Waste",
    "Highly Polluting Industries (HPIs)", "Land Degradation",
    "Climate Change and Greenhouse Gases (GHGs)",
    "Climate Change Impacts and IPCC Reports", "Climate Change Mitigation",
    "International Environmental Conventions and Laws – I",
    "International Environmental Conventions and Laws – II",
    "National Environmental Legislation – I",
    "National Environmental Legislation – Part II",
    "Green Revolution and Sustainable Agricultural Practices",
    "Energy Sources, Renewables and Energy Conservation", "Water Conservation",
    "Major Species and Invasive Species",
  ]},
  { name: "Modern History", emoji: "🏛️", chapters: [
    "Sources for the History of Modern India",
    "Major Approaches to the History of Modern India",
    "Advent of the Europeans in India", "India on the Eve of British Conquest",
    "Expansion and Consolidation of British Power in India",
    "People’s Resistance Against British Before 1857", "The Revolt of 1857",
    "Socio-Religious Reform Movements: General Features",
    "A General Survey of Socio-Cultural Reform Movements",
    "Beginning of Modern Nationalism in India",
    "Indian National Congress: Foundation and the Moderate Phase",
    "Era of Militant Nationalism (1905–1909)",
    "First Phase of Revolutionary Activities (1907–1917)",
    "First World War and Nationalist Response", "Emergence of Gandhi",
    "Non-Cooperation Movement and Khilafat Andolan",
    "Emergence of Swarajists, Socialist Ideas, Revolutionary Activities and Other New Forces",
    "Simon Commission and the Nehru Report",
    "Civil Disobedience Movement and Round Table Conferences",
    "Debates on the Future Strategy after Civil Disobedience Movement",
    "Congress Rule in Provinces",
    "Nationalist Response in the Wake of World War II",
    "Quit India Movement, Demand for Pakistan, and the INA",
    "Post-War National Scenario", "Independence with Partition",
    "Constitutional, Administrative and Judicial Developments",
    "Survey of British Policies in India",
    "Economic Impact of British Rule in India",
    "Development of Indian Press", "Development of Education",
    "Peasant Movements (1857–1947)", "The Movement of the Working Class",
    "Challenges Before the New-born Nation", "The Indian States",
    "Making of the Constitution for India",
    "The Evolution of Nationalist Foreign Policy", "First General Elections",
    "Developments under Nehru’s Leadership (1947–64)",
  ]},
  { name: "Ancient History", emoji: "🗿", chapters: [
    "The Significance of Ancient Indian History",
    "Modern Historians of Ancient India",
    "Nature of Sources and Historical Construction", "Geographical Setting",
    "Ecology and Environment", "The Linguistic Background",
    "Human Evolution: The Old Stone Age",
    "The Neolithic Age: First Food Producers and Animal Keepers",
    "Chalcolithic Cultures",
    "Harappan Culture: Bronze Age Urbanization in the Indus Valley",
    "Identity of Aryan Culture", "The Age of the Rig Veda",
    "The Later Vedic Phase: Transition to State and Social Orders",
    "Jainism and Buddhism", "Territorial States and the Rise of Magadha",
    "Iranian and Macedonian Invasions",
    "State Structure and the Varna System in the Age of the Buddha",
    "The Maurya Age", "The Significance of Maurya Rule",
    "Central Asian Contact and Mutual Impact", "The Satavahana Phase",
    "The Dawn of History in the Deep South",
    "Crafts, Commerce, and Urban Growth (200 BC–AD 250)",
    "Rise and Growth of the Gupta Empire", "Life in the Gupta Age",
    "Spread of Civilization in Eastern India", "Harsha and His Times",
    "Brahmanization, Rural Expansion, and Peasant Protest in the Peninsula",
    "Developments in Philosophy", "Cultural Interaction with Asian Countries",
    "From Ancient to Medieval", "Sequence of Social Changes",
    "Legacy in Science and Civilization",
  ]},
  { name: "Medieval History", emoji: "🕌", chapters: [
    "India and the World",
    "Northern India: Age of the Three Empires (800–1000)",
    "South India: The Chola Empire (900–1200)",
    "Economic and Social Life, Education and Religious Beliefs (800–1200)",
    "The Age of Conflict (Circa 1000–1200)",
    "The Delhi Sultanat—I (Circa 1200–1300)",
    "The Delhi Sultanat—II (Circa 1300–1400)",
    "Government, and Economic and Social Life under the Delhi Sultanat",
    "The Age of Vijayanagara and the Bahmanids, and the Coming of the Portuguese (Circa 1350–1565)",
    "Struggle for Empire in North India—I (Circa 1400–1525)",
    "Cultural Development in India (1200–1500)",
    "Struggle for Empire in North India—II Mughals and Afghans (1525–1555)",
    "Consolidation of the Mughal Empire Age of Akbar",
    "The Deccan and South India (Up to 1656)",
    "India in the First Half of the Seventeenth Century",
    "Economic and Social Life under the Mughals",
    "Cultural and Religious Developments",
    "Climax and Disintegration of the Mughal Empire—I",
    "Climax and Disintegration of the Mughal Empire—II",
    "Assessment and Review",
  ]},
  { name: "Art & Culture", emoji: "🎭", chapters: [
    "Indian Architecture", "Sculpture & Pottery", "Indian Paintings",
    "Performing Arts — Dance", "Music", "Theatre & Puppetry",
    "Languages & Literature", "Religions & Philosophy", "UNESCO Heritage",
  ]},
  { name: "Science & Technology", emoji: "🔬", chapters: [
    "Space Technology", "Defence Technology", "Biotechnology",
    "Nanotechnology", "IT & Computers", "Health & Diseases", "Energy",
  ]},
  { name: "International Relations", emoji: "🌐", chapters: [
    "India's Foreign Policy", "India & Neighbours", "India & Major Powers",
    "Groupings & Bilateral", "International Organizations", "Global Issues",
  ]},
  { name: "Internal Security", emoji: "🛡️", chapters: [
    "Terrorism", "Insurgency in NE", "Left Wing Extremism", "Cyber Security",
    "Money Laundering", "Border Management", "Security Forces & Agencies",
    "Disaster Management Basics",
  ]},
  { name: "Disaster Management", emoji: "🌪️", chapters: [
    "Types of Disasters", "Disaster Management Cycle", "Institutional Framework",
    "Floods & Droughts", "Earthquakes & Landslides", "Cyclones",
  ]},
  { name: "Agriculture", emoji: "🌾", chapters: [
    "Cropping Patterns", "Irrigation", "Agricultural Inputs", "Food Security",
    "Agricultural Marketing", "Animal Husbandry", "Government Schemes",
  ]},
  { name: "Society", emoji: "👥", chapters: [
    "Salient Features of Indian Society", "Diversity", "Role of Women",
    "Population & Demographics", "Urbanization", "Globalization & Society",
    "Social Empowerment", "Communalism & Regionalism",
  ]},
  { name: "Ethics", emoji: "🧭", chapters: [
    "Ethics & Human Interface", "Attitude", "Aptitude & Foundational Values",
    "Emotional Intelligence", "Contributions of Thinkers", "Public/Civil Service Values",
    "Probity in Governance", "Case Studies",
  ]},
  { name: "Essay", emoji: "✍️", chapters: [
    "Essay Structure & Approach", "Philosophical Essays", "Socio-Economic Essays",
    "Polity & Governance Essays", "Quotes & Practice",
  ]},
  { name: "Anthropology Optional", emoji: "🧬", chapters: [
    "Meaning & Scope", "Human Evolution", "Primates", "Physical Anthropology",
    "Archaeological Anthropology", "Social-Cultural Anthropology", "Kinship",
    "Marriage & Family", "Religion & Magic", "Economic Organization",
    "Political Organization", "Anthropological Theories", "Indian Anthropology",
    "Tribal India", "Applied Anthropology",
  ]},
];
